--
-- This script was generated by Valentina Studio
-- Application homepage: http://www.valentina-db.com/
--


-- --------------------------------------------------------------------------------
-- Populate Tables
-- --------------------------------------------------------------------------------

INSERT INTO "permissions" ("id","created_at","updated_at","deleted_at","name","action","subject","conditions","inverted","reason") VALUES 
( '019b835f-fd53-75ba-8ce8-aaf3b79179f3','2026-01-03 17:21:03.905674+07','2026-01-03 17:21:03.905674+07',NULL,'Super Admin','manage','all','','0',NULL ),
( '019b835f-fd53-75ba-8ce8-ae4d6059aad4','2026-01-03 17:21:03.905674+07','2026-01-03 17:21:03.905674+07',NULL,'Store','create','Store','','0',NULL ),
( '019b835f-fd53-75ba-8ce8-b16112c0fc0b','2026-01-03 17:21:03.905674+07','2026-01-03 17:21:03.905674+07',NULL,'Store','read','Store','{"ownerId": "$current_user_id"}','0',NULL ),
( '019b835f-fd53-75ba-8ce8-b4c2067a0c9c','2026-01-03 17:21:03.905674+07','2026-01-03 17:21:03.905674+07',NULL,'Store','update','Store','{"ownerId": "$current_user_id"}','0',NULL ),
( '019b835f-fd53-75ba-8ce8-b8a470f0e6b2','2026-01-03 17:21:03.905674+07','2026-01-03 17:21:03.905674+07',NULL,'Store','delete','Store','{"ownerId": "$current_user_id"}','0',NULL ),
( '019b836f-3e80-7029-b1f0-b63b81eefadc','2026-01-03 17:37:43.434945+07','2026-01-03 17:37:43.434945+07',NULL,'View Authenticated Resource','read','Auth','','0',NULL ),
( '019b8743-18db-7173-8ea8-df5692199e32','2026-01-04 11:28:00.065642+07','2026-01-04 11:28:00.065642+07',NULL,'Create Category','create','Category','{"storeId": "$current_store_id"}','0',NULL ),
( '019b8743-18dc-7065-8904-15fa913f60f1','2026-01-04 11:28:00.065642+07','2026-01-04 11:28:00.065642+07',NULL,'View Category','read','Category','{"storeId": "$current_store_id"}','0',NULL ),
( '019b8743-18dc-7065-8904-192a5db67bd8','2026-01-04 11:28:00.065642+07','2026-01-04 11:28:00.065642+07',NULL,'Update Category','update','Category','{"storeId": "$current_store_id"}','0',NULL ),
( '019b8743-18dc-7065-8904-1f3043a1e753','2026-01-04 11:28:00.065642+07','2026-01-04 11:28:00.065642+07',NULL,'Delete Category','delete','Category','{"storeId": "$current_store_id"}','0',NULL ),
( '019b8c21-f2e3-728e-8d4c-168673222fc8','2026-01-05 10:09:54.517632+07','2026-01-05 10:09:54.517632+07',NULL,'Create Product','create','Product','{"storeId": "$current_store_id"}','0',NULL ),
( '019b8c21-f2e3-728e-8d4c-18c71b73b68d','2026-01-05 10:09:54.517632+07','2026-01-05 10:09:54.517632+07',NULL,'View Product','read','Product','{"storeId": "$current_store_id"}','0',NULL ),
( '019b8c21-f2e3-728e-8d4c-1d9f7a3ba3f6','2026-01-05 10:09:54.517632+07','2026-01-05 10:09:54.517632+07',NULL,'Update Product','update','Product','{"storeId": "$current_store_id"}','0',NULL ),
( '019b8c21-f2e3-728e-8d4c-230a8add5e2a','2026-01-05 10:09:54.517632+07','2026-01-05 10:09:54.517632+07',NULL,'Delete Product','delete','Product','{"storeId": "$current_store_id"}','0',NULL ),
( '019b8c71-7f8e-74c9-85b1-f1123f772954','2026-01-05 11:36:47.502922+07','2026-01-05 11:36:47.502922+07',NULL,'Create Recommendation','create','Recommendation','{"storeId": "$current_store_id"}','0',NULL ),
( '019b8c71-7f8e-74c9-85b1-f6be3379e308','2026-01-05 11:36:47.502922+07','2026-01-05 11:36:47.502922+07',NULL,'View Recommendation','read','Recommendation','{"storeId": "$current_store_id"}','0',NULL ),
( '019b8c71-7f8e-74c9-85b1-f848594c0d83','2026-01-05 11:36:47.502922+07','2026-01-05 11:36:47.502922+07',NULL,'Update Recommendation','update','Recommendation','{"storeId": "$current_store_id"}','0',NULL ),
( '019b8c71-7f8e-74c9-85b1-fef894d5ed86','2026-01-05 11:36:47.502922+07','2026-01-05 11:36:47.502922+07',NULL,'Delete Recommendation','delete','Recommendation','{"storeId": "$current_store_id"}','0',NULL )

