--
-- This script was generated by Valentina Studio
-- Application homepage: http://www.valentina-db.com/
--


-- --------------------------------------------------------------------------------
-- Populate Tables
-- --------------------------------------------------------------------------------

INSERT INTO "roles" ("id","created_at","updated_at","deleted_at","name","description") VALUES 
( '019b6490-95c3-73ad-9101-93d04967c777','2026-01-03 17:18:13.512354+07','2026-01-03 17:18:13.512354+07',NULL,'SUPER_ADMIN',NULL ),
( '019b6490-95c4-7693-abd0-92395f3ae5a7','2026-01-03 17:18:13.512354+07','2026-01-03 17:18:13.512354+07',NULL,'ADMIN',NULL ),
( '019b6490-95c4-7693-abd0-95451672a814','2026-01-03 17:18:13.512354+07','2026-01-03 17:18:13.512354+07',NULL,'USER',NULL )

