--
-- This script was generated by Valentina Studio
-- Application homepage: http://www.valentina-db.com/
--


-- --------------------------------------------------------------------------------
-- Populate Tables
-- --------------------------------------------------------------------------------

INSERT INTO "roles" ("id","name","description") VALUES 
( '019b6490-95c3-73ad-9101-93d04967c777','SUPER ADMIN',NULL ),
( '019b6490-95c4-7693-abd0-92395f3ae5a7','ADMIN',NULL ),
( '019b6490-95c4-7693-abd0-95451672a814','USER',NULL )

