--
-- This script was generated by Valentina Studio
-- Application homepage: http://www.valentina-db.com/
--


-- --------------------------------------------------------------------------------
-- Populate Tables
-- --------------------------------------------------------------------------------

INSERT INTO `permissions` (`id`,`name`,`action`,`subject`,`conditions`,`inverted`,`reason`) VALUES 
( '019b5061-d8f0-77e8-aabf-a48280ec67c8','ManageAll','manage','all','','0',NULL ),
( '019b5061-d8f1-75ca-bd5a-f18d1bbd9245','Bank','create','Bank','{"store_id": "{{current_store_id}}"}','0',NULL ),
( '019b5061-d8f1-75ca-bd5a-f59d286bfbda','Bank','read','Bank','{"store_id": "{{current_store_id}}"}','0',NULL ),
( '019b5061-d8f1-75ca-bd5a-f9d6f8f325c8','Bank','update','Bank','{"store_id": "{{current_store_id}}"}','0',NULL ),
( '019b5061-d8f1-75ca-bd5a-feb5cd1e20c9','Bank','delete','Bank','{"store_id": "{{current_store_id}}"}','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-03baf54bd772','Category','create','Category','{"store_id": "{{current_store_id}}"}','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-05c2bb7db954','Category','read','Category','{"store_id": "{{current_store_id}}"}','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-0b482ad11ec3','Category','update','Category','{"store_id": "{{current_store_id}}"}','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-0df3a27f696f','Category','delete','Category','{"store_id": "{{current_store_id}}"}','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-10bb5afdadfd','Ingredient','create','Ingredient','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-179b26d9f2e7','Ingredient','read','Ingredient','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-1aadf0e95f2f','Ingredient','update','Ingredient','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-1f9af59f9b89','Ingredient','delete','Ingredient','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-20d3d38ce4a2','Product','create','Product','{"store_id": "{{current_store_id}}"}','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-24030be96d83','Product','read','Product','{"store_id": "{{current_store_id}}"}','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-2a45849372d7','Product','update','Product','{"store_id": "{{current_store_id}}"}','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-2d08194972a4','Product','delete','Product','{"store_id": "{{current_store_id}}"}','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-313845d85be1','ProductCategory','create','ProductCategory','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-356e9632efcc','ProductCategory','read','ProductCategory','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-38b6c00ec109','ProductCategory','update','ProductCategory','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-3e3469596645','ProductCategory','delete','ProductCategory','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-401d91522e4c','ProductIngredient','create','ProductIngredient','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-443c83daa171','ProductIngredient','read','ProductIngredient','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-486f5aca6645','ProductIngredient','update','ProductIngredient','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-4cd26a1baa24','ProductIngredient','delete','ProductIngredient','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-53f74adc1ff7','Store','create','Store','{"owner": "{{current_user_id}}"}','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-56728fe95dd9','Store','read','Store','{"owner": "{{current_user_id}}"}','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-5a228edb902c','Store','update','Store','{"owner": "{{current_user_id}}"}','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-5f922d0dc0bb','Store','delete','Store','{"owner": "{{current_user_id}}"}','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-63b864aa2b52','Subscription','create','Subscription','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-67e2ecfeb4d3','Subscription','read','Subscription','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-69e50c45bc5c','Subscription','update','Subscription','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-6f83a1b2cf43','Subscription','delete','Subscription','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-725fa359aa47','SubscriptionPayment','create','SubscriptionPayment','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-75b6d0244416','SubscriptionPayment','read','SubscriptionPayment','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-795d73941d90','SubscriptionPayment','update','SubscriptionPayment','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-7ed81f8f6b6b','SubscriptionPayment','delete','SubscriptionPayment','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-8271d1836485','Transaction','create','Transaction','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-86eb764e0122','Transaction','read','Transaction','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-8b9d08e64207','Transaction','update','Transaction','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-8f86d35d341f','Transaction','delete','Transaction','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-9286ea20b795','TransactionDetail','create','TransactionDetail','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-9667dd89f756','TransactionDetail','read','TransactionDetail','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-9bf0a44de70a','TransactionDetail','update','TransactionDetail','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-9f91e4f522e4','TransactionDetail','delete','TransactionDetail','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-a2a77f49138c','User','create','User','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-a49313bd290b','User','read','User','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-ab83091729e0','User','update','User','','0',NULL ),
( '019b5061-d8f1-75ca-bd5b-ac0788ce18de','User','delete','User','','0',NULL )

